### ISSUE TITLE
on IOS the native call returns "Not Flight Mode" and a late initialization error occurs

### ISSUE THREAD

**Issue by dickverweij** [14h4i/airplane_mode_checker#1]
see this code snippet:

![image](https://user-images.githubusercontent.com/8133838/155137518-07d6c5fd-d557-4922-989b-f7ccbcabbfc1.png)

**Comment by dickverweij** [comment]
you fixed this in https://github.com/14h4i/airplane_mode_checker/pull/3, but is the pub.dev version upgraded?

**Comment by 14h4i** [comment]
> you fixed this in #3, but is the pub.dev version upgraded?

Sorry for the slow response, I updated the package to a new version

**Comment by 14h4i** [comment]
Sorry for the slow response, I updated the package to a new version. I will close this issue.
