### ISSUE TITLE
Wrong Status for No SIM Mobile

### ISSUE THREAD

**Issue by nvalakunde** [14h4i/airplane_mode_checker#10]
If SIM is not available and Wifi is off it gives status as AirplaneModeStatus.on

**Comment by 14h4i** [comment]
@nvalakunde  I'm sorry but it seems that IOS can't detect airplane mode correctly but can only detect it when device's connections are OFF (SIM is not available and Wifi is off)
Currently I have not found any other solution. I will update the code when there is a better solution. And if you or someone else has a solution, please contribute to me.
Thank you.
