### ISSUE TITLE
AirplaneModeStatus is false when connected in wifi but flight Mode ON

### ISSUE THREAD

**Issue by mariganesh55** [14h4i/airplane_mode_checker#11]
If we connected the mobile with WIFI network, and flight mode is ON, The AirplaneModeStatus status returns false. It returns false instead of true.

**Comment by hardiklycrosys** [comment]
@mariganesh55 did you got any solution on this? I am also facing same issue on ios.

**Comment by mariganesh55** [comment]
@hardiklycrosys I handled this case with native code. It worked for me.

import CoreTelephony
private func isAirplaneModeOn() -> Bool {
        let networkInfo = CTTelephonyNetworkInfo()
          guard let radioAccessTechnology = networkInfo.serviceCurrentRadioAccessTechnology else {
            return false
          }
          return radioAccessTechnology.isEmpty
      }

**Comment by hardiklycrosys** [comment]
@mariganesh55 thanks for your response,

can you let me know step by step for write native code for ios and how we can get status in dart file for ios?

**Comment by sachinbpatil619** [comment]
@mariganesh55 Can you explain how you fixed it. I am also facing the same issue.

**Comment by 14h4i** [comment]
@hardikmobituts @sachinbpatil619 Sorry for the late response, I have fixed and it is available in version 2.1.0.
Thanks you @mariganesh55 for giving me the solution.
