### ISSUE TITLE
AirplaneModeStatus is ON when connected in wifi and Airplane Mode is OFF

### ISSUE THREAD

**Issue by ShinJinBum** [14h4i/airplane_mode_checker#13]
This is probably a bug caused by #11.

It worked well in 2.0.0, but in 2.1.0, the result of checkAirplaneMode() is ON even though I did not turn on airplane mode in iOS.

This doesn't happen on Android.

**Comment by ShinJinBum** [comment]
After further testing, some iPhones work and some do not. I don't know what the difference is, but the phones with the bug are the 15 Pro Max (emulator) and the 12 mini.

**Comment by 14h4i** [comment]
@ShinJinBum The plugin determines airplane mode based on the device's cellular service. Since you are using a IOS emulator (no SIM - cellular service), airplane mode is always ON.
You can check again on the physical device.
Thank you.
