### ISSUE TITLE
Support for AGP Version >= 8.X.X

### ISSUE THREAD

**Issue by arconsis-micha** [14h4i/airplane_mode_checker#15]
Hello there,

Currently I'm updating a Flutter project to the newest state possible.
When updating Gradle I get a ```Namespace not specified.``` error from airplane_mode_checker.

Since AGP 8 and newer a namespace value is needed in ```app/build.gradle``` file and removed from ```AndroidManifest.xml```

```
android {
...
    namespace 'com.u14h4i.airplane_mode_checker'
...
}
```

Please have a look at this [StackOverflow thread](https://stackoverflow.com/questions/76108428/how-do-i-fix-namespace-not-specified-error-in-android-studio).

Maybe you consider this part in the next update. :D

Thank you very much!

**Comment by 14h4i** [comment]
@arconsis-micha Thanks for letting me know. I added `namespace` to the plugin in the [PR](https://github.com/14h4i/airplane_mode_checker/pull/17).
And it's available in version [3.0.0](https://pub.dev/packages/airplane_mode_checker)
