### ISSUE TITLE
Emit Stream state

### ISSUE THREAD

**Issue by thorito** [14h4i/airplane_mode_checker#16]
Is it possible to emit a stream when the state changes?
Thanks

**Comment by 14h4i** [comment]
@thorito Thanks for your suggestion. I added new feature `AirplaneModeChecker.instance.listenAirplaneMode()` for Stream - [PR#18](https://github.com/14h4i/airplane_mode_checker/pull/18). 
Now It is available in version [3.1.0](https://pub.dev/packages/airplane_mode_checker/versions/3.1.0)
