### ISSUE TITLE
iOS airplane mode always ON when app running on iPad WiFi (without cellular)

### ISSUE THREAD

**Issue by alex-melnyk** [14h4i/airplane_mode_checker#20]
So when I run my app on on iPad WiFi (without cellular) the `AirplaneModeChecker.instance.checkAirplaneMode()` always returns `AirplaneModeStatus.on` which is not correct due to WiFi connection is established.

**Comment by 14h4i** [comment]
@alex-melnyk 
Currently, my code determines airplane mode by checking cellular connectivity using `CTTelephonyNetworkInfo`. On WiFi-only devices like an iPad, there's no cellular connection, so this property is always empty, resulting in an "ON" status for airplane mode.

Additionally, users can enable WiFi even when airplane mode is activated, making it unreliable to use WiFi status to determine airplane mode. Therefore, my method relies solely on cellular network information for accurate airplane mode detection.

If there are no further questions or concerns, I will proceed to close this issue. Thank you for bringing this to my attention, and feel free to reach out if you have any other inquiries or need further assistance.
