### ISSUE TITLE
Module 'airplane_mode_checker' not found

### ISSUE THREAD

**Issue by jlucas577** [14h4i/airplane_mode_checker#4]
I'm getting the following error when trying to compile my project for iOS release mode: Module 'airplane_mode_checker' not found

What could it be?

Error:
<img width="756" alt="Captura de Tela 2022-08-11 às 18 42 05" src="https://user-images.githubusercontent.com/39962531/184247406-30908399-d3d9-47fe-80a9-4515894443b6.png">

Flutter doctor:
![Captura de Tela 2022-08-11 às 18 43 20](https://user-images.githubusercontent.com/39962531/184247570-1549370c-6952-4d26-a681-2f6c2e39b799.png)

I'm using: 
`airplane_mode_checker: ^1.0.2`

**Comment by 14h4i** [comment]
@jlucas577 Sorry for the late reply. Please check the following link to see if you get the same error.
https://github.com/flutter/flutter/issues/43986#issuecomment-612615174
Please open `ios/Runner.xcworkspace` instead of `ios/Runner.xcodeproj` on Xcode.
