### ISSUE TITLE
Plugin showing off when the airplane mode is on in IOS 

### ISSUE THREAD

**Issue by Priyanshu078** [14h4i/airplane_mode_checker#5]
In iphone and ipad when I am having airplane mode on and wifi is not connected.
Plugin shows airplane mode is ON.
But when I connect to any wifi while the airplane mode in ON in ios device. so the airplane mode status shows airplane mode is Off.
I am not able to figure it out, why it is giving the status off when the airplane mode is ON.

**Comment by 14h4i** [comment]
@Priyanshu078 I'm sorry but it seems that IOS can't detect airplane mode correctly but can only detect it through WIFI.
Currently I have not found any other solution. I will update the code when there is a better solution. And if you or someone else has a solution, please contribute to me.
Thank you.
