### ISSUE TITLE
Remove print statements to avoid spamming the logs

### ISSUE THREAD

**Issue by JulianBissekkou** [14h4i/airplane_mode_checker#7]
Title says it all :P

**Comment by stefanschaller** [comment]
@14h4i  Is fixed in: https://github.com/14h4i/airplane_mode_checker/pull/8

**Comment by 14h4i** [comment]
@JulianBissekkou The issues has been resolved in new version ([1.0.5](https://pub.dev/packages/airplane_mode_checker)).
Thank you @stefanschaller.
