### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by AdrianDev0** [14h4i/airplane_mode_checker#9]
Could you update your versions? I am getting errors from your library versions when trying to update my project to use the latest AGP version.

* Android Gradle plugin (AGP)
* Gradle wrapper
* Kotlin version
* compileSdkVersion
* Update dependencies

**Comment by saropa** [comment]
Hi, I am unsure if it related to the version issue but I am getting compile warnings with this package:

> \Pub\Cache\hosted\pub.dev\airplane_mode_checker-1.0.5\android\src\main\java\com\u14h4i\airplane_mode_checker\AirplaneModeCheckerPlugin.java uses or overrides a deprecated API.

**Comment by AdrianDev0** [comment]
Hm, it seems something in the file is deprecated. Can you just update that deprecation, too?

**Comment by 14h4i** [comment]
Thank you @AdrianDev0 @saropa for reporting.
I updated:
* Android Gradle plugin (AGP)
* Gradle wrapper
* Kotlin version
* compileSdkVersion
* Update dependencies

And the package has been released in the latest version
```yaml
dependencies:
  airplane_mode_checker: ^2.0.0
```

**Comment by 14h4i** [comment]
If there is no problem, I will close this issue
